apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086

    isDefault: true
    editable: false

    jsonData:
      version: Flux
      organization: TEKO
      defaultBucket: sensor_data

    secureJsonData:
      token: teko-database-design-token
